### ISSUE TITLE
提供开关控制是否保存历史数据

### ISSUE THREAD

**Issue by Gahon1995** [MemoryZy/Json-Assistant#45]
### 需求/建议描述

- 存在很多大json的时候，如果保存历史记录，会导致获取的时候很卡。
- 部分json保存的时候会提示 `data '' is not legal for a JDOM attribute: 0x001d is not a legal XML character`

### 建议的解决方案

- 提供全局设置不保存历史记录

**Comment by MemoryZy** [comment]
不会的，保存历史记录是在你的焦点离开侧边窗口后，用异步线程执行的，不影响主UI线程。

而且你这个问题，我建议你在这个异常下次出现的时候，点击Report to Vendor。或者粘贴异常到这个issue。

**Comment by MemoryZy** [comment]
并且，这个异常看起来像是在解析XML Dom文档时，出现了一个非法字符，但是不应出现在JSON处理中。

可以把堆栈发我，我验证一下是不是插件的问题。

**Comment by Gahon1995** [comment]
- 我的json很大，然后打开那个历史页面，点击选择不同请求的时候感觉会卡顿一下

- 至于保存的时候报错，应该是我的json里边有特殊字符导致xml配置文件解析异常了，等我后边看看能不能复现一下看是啥字符导致异常

**Comment by MemoryZy** [comment]
这样的话，那我就加一个开关吧。

**Comment by Gahon1995** [comment]
一个异常堆栈如下，其中我的jsonData数据应该有十几M左右
```
WARN - #c.i.o.c.i.s.StoreUtil - Save settings failed
java.lang.Exception: Cannot get JsonAssistantHistoryState component state
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponents$suspendImpl(ComponentStoreImpl.kt:283)
	at com.intellij.configurationStore.ComponentStoreImpl$commitComponents$1.invokeSuspend(ComponentStoreImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
Caused by: org.jdom.IllegalDataException: The data "xxx" is not legal for a JDOM attribute: 0x001d is not a legal XML character.
	at org.jdom.Attribute.setValue(Attribute.java:394)
	at org.jdom.ImmutableAttribute.<init>(ImmutableAttribute.java:9)
	at org.jdom.ImmutableSameTypeAttributeList.get(ImmutableSameTypeAttributeList.java:24)
	at org.jdom.ImmutableSameTypeAttributeList.get(ImmutableSameTypeAttributeList.java:10)
	at com.intellij.openapi.util.JDOMUtil.isAttributesEqual(JDOMUtil.java:181)
	at com.intellij.openapi.util.JDOMUtil.areElementsEqual(JDOMUtil.java:80)
	at com.intellij.openapi.util.JDOMUtil.areElementsEqual(JDOMUtil.java:68)
	at com.intellij.configurationStore.StateMapKt.setStateAndCloneIfNeeded(StateMap.kt:125)
	at com.intellij.configurationStore.XmlElementStorage$XmlElementStorageSaveSessionProducer.setSerializedState(XmlElementStorage.kt:298)
	at com.intellij.configurationStore.SaveSessionProducerBase.setState(StateStorageBase.kt:144)
	at com.intellij.configurationStore.ComponentStoreImpl.setStateToSaveSessionProducer(ComponentStoreImpl.kt:399)
	at com.intellij.configurationScript.providers.MyProjectStore.setStateToSaveSessionProducer(ConfigurationScriptProjectStoreFactory.kt:97)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponent(ComponentStoreImpl.kt:386)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponents$suspendImpl(ComponentStoreImpl.kt:279)
	... 10 more
```

**Comment by MemoryZy** [comment]
IDEA本身是通过xml序列化/反序列化来进行持久化，大概是在反序列化时，解析到了非法字符。

**Comment by MemoryZy** [comment]
请下载 [v1.7.5](https://github.com/MemoryZy/Json-Assistant/releases/tag/v1.7.5) 版本。
